# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"load_train": "00_helpers.ipynb",
         "show_img": "00_helpers.ipynb"}

modules = ["helpers.py"]

doc_url = "https://thurgarion2.github.io/noise2noise/"

git_url = "https://github.com/thurgarion2/noise2noise/tree/{branch}/"

def custom_doc_links(name): return None
