# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"RandomResizedCrop": "00_augmentation.ipynb",
         "RandomRotation": "00_augmentation.ipynb",
         "load_images": "00_helpers.ipynb",
         "to_float_image": "00_helpers.ipynb",
         "to_rgb_image": "00_helpers.ipynb",
         "show_img": "00_helpers.ipynb",
         "psnr": "00_helpers.ipynb",
         "ToFloatImage": "00_training.ipynb",
         "Noise2NoiseDataset": "00_training.ipynb",
         "psnr_metric": "00_training.ipynb",
         "train": "00_training.ipynb",
         "eval_model": "00_training.ipynb",
         "show_results": "00_training.ipynb",
         "plot_losses": "00_training.ipynb",
         "lr_finder": "00_training.ipynb",
         "UnetBlockDown": "00_unet.ipynb",
         "UnetBlockUp": "00_unet.ipynb",
         "UnetBlockDownBatchNorm": "00_unet.ipynb",
         "UnetBlockUpBatchNorm": "00_unet.ipynb",
         "Unet": "00_unet.ipynb",
         "UnetBatchNorm": "00_unet.ipynb",
         "ResNetBlock": "00_unet_resnet.ipynb",
         "ResizeBlock": "00_unet_resnet.ipynb",
         "ResNetUnet": "00_unet_resnet.ipynb",
         "ResNetUnetNotPretrained": "00_unet_resnet.ipynb"}

modules = ["augmentation.py",
           "helpers.py",
           "training.py",
           "unet.py",
           "unet_resnet.py"]

doc_url = "https://thurgarion2.github.io/noise2noise/"

git_url = "https://github.com/thurgarion2/noise2noise/tree/{branch}/"

def custom_doc_links(name): return None
