# AUTOGENERATED! DO NOT EDIT! File to edit: 00_helpers.ipynb (unless otherwise specified).

__all__ = ['load_train', 'show_img']

# Cell
import torch
from .loaddata import *
import matplotlib.pyplot as plt

# Cell
def load_train(path="./dataset/train_data.pkl"):
    return torch.load(path)

# Cell

def show_img(tensor_img):
    plt.imshow(tensor_img.permute(1, 2, 0) )