# AUTOGENERATED! DO NOT EDIT! File to edit: 00_loaddata.ipynb (unless otherwise specified).

__all__ = ['load_train']

# Cell
#hide
import torch
import matplotlib.pyplot as plt

# Cell
def load_train(path="./dataset/train_data.pkl"):
    return torch.load(path)