# AUTOGENERATED! DO NOT EDIT! File to edit: 00_training_pytorch.ipynb (unless otherwise specified).

__all__ = ['to_float_image', 'ToFloatImage']

# Cell
import torch

from torch.utils.data import DataLoader, Dataset
from torchvision import transforms


# Cell
def to_float_image(image):
    return image.float()/255

# Cell
class ToFloatImage:

    def __init__(self):
       pass

    def __call__(self, img):
        return to_float_image(img)